### ISSUE TITLE
Cant this published as a plugin?

### ISSUE THREAD

**Issue by am2222** [fnicollet/Leaflet#11]
This feature is a very useful one, But is not it possible to share this as a leaflet plugin?

**Comment by fnicollet** [comment]
Hello @am2222 ,

Leaflet-rotate makes some pretty big changes to the core code of leaflet, so it is not a really good candidate for a plugin but rather a new "feature" of a future leaflet version that would be integrated into the core. My branch has been ported to leaflet official project as the "rotate" branch for future work, so hopefully in a version of leaflet, the rotate parameter will be available

Fabien

**Comment by am2222** [comment]
Well I hope they integrate this package into core soon, It seems it is in their plan but there is not any specific time for that.
