### ISSUE TITLE
Default Marker Shadow Rotates Oddly

### ISSUE THREAD

**Issue by marioatmicello** [fnicollet/Leaflet#13]
When using the default blue marker and the bearing is set to a non-zero number, the drop shadow for the marker is rotated oddly. I would expect the shadow to look the same as when the bearing is 0. Attached is a screen shot (the markers are part of a FeatureGroup which also includes the Micello Indoor Map you see as well):

![leafletrotatemarkershadow](https://cloud.githubusercontent.com/assets/23269621/20079653/7778f15a-a4fa-11e6-85ab-028136f171f2.png)

**Comment by fnicollet** [comment]
Are the examples in:
https://github.com/fnicollet/Leaflet/tree/master/debug/map
Working for you? Try rotate.html
If not, are you up-to-date on this branch?

**Comment by marioatmicello** [comment]
Yes, this one is my bad. Close the issue. Updating my build resolved this. Sorry about that.
