### ISSUE TITLE
Add PlugIns

### ISSUE THREAD

**Issue by kaio328** [fnicollet/Leaflet#15]
Hey there,

am i doing something wrong or is it not possible to combine this with other leaflet plugins? For example L.Control-Search.

Greetz.

**Comment by fnicollet** [comment]
Hello,

Actually never tried adding other plugins with the rotate branch. Do they
work with leaflet 1.0.3 master?
What happens when you use the rotate branch? Errors in the console?
Jsfiddle would be nice

Fabien

**Comment by kaio328** [comment]
Thanks for that fast reply! I could figure out where my problem was and fixed it quickly. It was very simple:  		
```
<script src="folder/leaflet1.0.2.js"></script>
<script src="folder/deps.js"></script>
<script src="folder/leaflet-include.js"></script
```
They have to be set before any other .js data in the head. Works pretty well! Great "plugin" by the way! Because of this one i didnt switch my project to mapbox/openLayers3. Great job!

**Comment by fnicollet** [comment]
Great :)
