### ISSUE TITLE
Using rotate-master with cartodb.js?

### ISSUE THREAD

**Issue by jdgodchaux** [fnicollet/Leaflet#17]
Hello!

My colleague and I are trying to implement Leaflet rotation for a map were building using cartodb.js. Our problem is that cartodb.js is dependent on Leaflet 0.7.3 and it appears that is built on the 1.0 version of Leaflet. I couldn't find in the `rotate-master` repo a place where the rotation functionality was developed in Leaflet 0.7.x. Does this exist? If so, can you please point me to a commit in `rotate-master` that has map rotation implemented on Leaflet 0.7.x?

Thank you!!
JD

**Comment by fnicollet** [comment]
Hello,

Unfortunately, leaflet-rotate was created based on leaflet 1.x, never on 0.7.x. I don't even know if that's possible to backport it to 0.7 as the trick for rotation is mostly based on the new "panes" system introduced in 1.x

Fabien
