### ISSUE TITLE
use rotate with my project

### ISSUE THREAD

**Issue by zhuyinjing** [fnicollet/Leaflet#30]
hey,
i use `"leaflet": "^1.2.0"`
and i want to rotate my map with your rotate function.
how can i add rotate function to my code?
i need your help. 
Thanks so much!

**Comment by fnicollet** [comment]
Hello,

Please use the "rotate-master" branch, you will need to build this version yourself, this version is a fork and is not published on NPM. Then follow the instructions in the README:
https://github.com/fnicollet/Leaflet/tree/rotate-master

Thanks,
Fabien
