### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by aquananu** [fnicollet/Leaflet#34]
hi the examples are using rawgit.com which is no longer serving the files hence the samples are broken.

Kindly advise if this plug in still works

**Comment by fnicollet** [comment]
Hello,

I haven't worked on this for years, it is not maintained anymore, and most probabmy doesn't work with recent versions of leaflet. 
Please seek other solutions. There are other "hacky" projects, but if you really want rotation as a feature, please try using MapLibre or OpenLayers

Fabien
